// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPUjDPS0bzhUS_xi7O05T3b2ioU1S1AJ0',
    appId: '1:930014099292:web:61fca4d0d137d9ee627399',
    messagingSenderId: '930014099292',
    projectId: 'lenguas-6706d',
    authDomain: 'lenguas-6706d.firebaseapp.com',
    storageBucket: 'lenguas-6706d.appspot.com',
    measurementId: 'G-FCE5J35N8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvOOhBNl7lFojFHlZLDl851PcJpVFzuXs',
    appId: '1:930014099292:android:03884a021b2ec8a2627399',
    messagingSenderId: '930014099292',
    projectId: 'lenguas-6706d',
    storageBucket: 'lenguas-6706d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoeKTd9JiHLxXuOv6QBtJKrZsS84aCy-s',
    appId: '1:930014099292:ios:d064592bef36d663627399',
    messagingSenderId: '930014099292',
    projectId: 'lenguas-6706d',
    storageBucket: 'lenguas-6706d.appspot.com',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoeKTd9JiHLxXuOv6QBtJKrZsS84aCy-s',
    appId: '1:930014099292:ios:c221f468dd2698cc627399',
    messagingSenderId: '930014099292',
    projectId: 'lenguas-6706d',
    storageBucket: 'lenguas-6706d.appspot.com',
    iosBundleId: 'com.example.app1.RunnerTests',
  );
}
